// <auto-generated />
using System;
using Gastos.Backup.Repositories.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gastos.Backup.Repositories.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Gastos.Backup.Core.Entities.ApartadoEntity", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("CantidadFinal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("CantidadInicial")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaDeRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaFinal")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaInicial")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Intereses")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("PeriodoGuid")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SubcategoriaGuid")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TipoDeApartadoGuid")
                        .HasColumnType("char(36)");

                    b.HasKey("Guid");

                    b.HasIndex("SubcategoriaGuid");

                    b.HasIndex("TipoDeApartadoGuid");

                    b.ToTable("Apartado");
                });

            modelBuilder.Entity("Gastos.Backup.Core.Entities.CategoriaEntity", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Guid");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("Gastos.Backup.Core.Entities.CompraEntity", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaDeRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MesesSinIntereses")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nota")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TdcId")
                        .HasColumnType("int");

                    b.HasKey("Guid");

                    b.ToTable("Compra");
                });

            modelBuilder.Entity("Gastos.Backup.Core.Entities.DetalleDeApartadoEntity", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("ApartadoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaDeRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nota")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Guid");

                    b.ToTable("DetalleDeApartado");
                });

            modelBuilder.Entity("Gastos.Backup.Core.Entities.GastoEntity", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaDeRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("PeriodoId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SubcategoriaId")
                        .HasColumnType("char(36)");

                    b.HasKey("Guid");

                    b.HasIndex("SubcategoriaId");

                    b.ToTable("Gasto");
                });

            modelBuilder.Entity("Gastos.Backup.Core.Entities.PagoEntity", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("CantidadDepositada")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("CantidadEsperada")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("CompraId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("FechaDeDeposito")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaDePago")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NumeroDePago")
                        .HasColumnType("int");

                    b.HasKey("Guid");

                    b.HasIndex("CompraId");

                    b.ToTable("Pago");
                });

            modelBuilder.Entity("Gastos.Backup.Core.Entities.PeriodoEntity", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaFinal")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaInicial")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Guid");

                    b.ToTable("Periodo");
                });

            modelBuilder.Entity("Gastos.Backup.Core.Entities.SubcategoriaEntity", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("CategoriaGuid")
                        .HasColumnType("char(36)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Guid");

                    b.HasIndex("CategoriaGuid");

                    b.ToTable("Subcategoria");
                });

            modelBuilder.Entity("Gastos.Backup.Core.Entities.TipoDeApartadoEntity", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Guid");

                    b.ToTable("TipoDeApartado");
                });

            modelBuilder.Entity("Gastos.Backup.Core.Entities.ApartadoEntity", b =>
                {
                    b.HasOne("Gastos.Backup.Core.Entities.SubcategoriaEntity", "Subcategoria")
                        .WithMany()
                        .HasForeignKey("SubcategoriaGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gastos.Backup.Core.Entities.TipoDeApartadoEntity", "TipoDeApartado")
                        .WithMany()
                        .HasForeignKey("TipoDeApartadoGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subcategoria");

                    b.Navigation("TipoDeApartado");
                });

            modelBuilder.Entity("Gastos.Backup.Core.Entities.GastoEntity", b =>
                {
                    b.HasOne("Gastos.Backup.Core.Entities.SubcategoriaEntity", "Subcategoria")
                        .WithMany()
                        .HasForeignKey("SubcategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subcategoria");
                });

            modelBuilder.Entity("Gastos.Backup.Core.Entities.PagoEntity", b =>
                {
                    b.HasOne("Gastos.Backup.Core.Entities.CompraEntity", "Compra")
                        .WithMany("ListaDePagos")
                        .HasForeignKey("CompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compra");
                });

            modelBuilder.Entity("Gastos.Backup.Core.Entities.SubcategoriaEntity", b =>
                {
                    b.HasOne("Gastos.Backup.Core.Entities.CategoriaEntity", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Gastos.Backup.Core.Entities.CompraEntity", b =>
                {
                    b.Navigation("ListaDePagos");
                });
#pragma warning restore 612, 618
        }
    }
}
